### ISSUE TITLE
兄弟，直接搜索替换全选是不行的

### ISSUE THREAD

**Issue by Jiaocz** [ods-im/ods-im#1]
我的仓库还有Github Action，不是说直接复制粘贴就可以解决的，博客文章和最近动态都是自动更新的，现在很多都是死链．

**Comment by vlianx** [comment]
我只是新发现的这个东西，觉得挺好。我就复制过来改了一下试试。😂我对这其实不了解的。你就当我是个小白吧

**Comment by Jiaocz** [comment]
好的吧，就是说一声，因为那个**My Work**里面的图片是打不开的链接是不对的，Github的readme是可以md和html混用的所以如果md看不懂的地方可以用html替换。
我的readme里面用到的东西：
- [自动获取博客文章](https://github.com/gautamkrishnar/blog-post-workflow)
- [获取最近动态](https://github.com/jamesgeorge007/github-activity-readme)
- [统计卡片](https://github.com/anuraghazra/github-readme-stats/blob/master/docs/readme_cn.md)

给你看一个有意思的简介，甚至可以在里面玩国际象棋
https://github.com/timburgan/timburgan

**Comment by vlianx** [comment]
好的，谢谢。我研究一下
